package com.bala.ims.IMSDataConversion.model;

import java.util.Date;

public class HDBPOVRData {

	private String HDBPOVR_PRDT_VARN; 		
	private String HDBPOVR_RGN_CDE; 		
	private Date HDBPOVR_EFF_DTE; 			
	private Date HDBPOVR_END_DTE;
	private String HDBPOVR_CNCL_RSN_CDE;
	private Double HDBPOVR_OVRIDE_PRC;
	private Double HDBPOVR_OVRIDE_PRC_ANES;
	private char HDBPOVR_OVRIDE_RSN_CDE;
	private String HDBPOVR_OVRIDE_RSN_TXT;
	private Date HDBPOVR_LAST_UPDT_DTE;
	private String HDBPOVR_LAST_USERID;
	
	public String getHDBPOVR_PRDT_VARN() {
		return HDBPOVR_PRDT_VARN;
	}
	public void setHDBPOVR_PRDT_VARN(String hDBPOVR_PRDT_VARN) {
		HDBPOVR_PRDT_VARN = hDBPOVR_PRDT_VARN;
	}
	public String getHDBPOVR_RGN_CDE() {
		return HDBPOVR_RGN_CDE;
	}
	public void setHDBPOVR_RGN_CDE(String hDBPOVR_RGN_CDE) {
		HDBPOVR_RGN_CDE = hDBPOVR_RGN_CDE;
	}
	public Date getHDBPOVR_EFF_DTE() {
		return HDBPOVR_EFF_DTE;
	}
	public void setHDBPOVR_EFF_DTE(Date hDBPOVR_EFF_DTE) {
		HDBPOVR_EFF_DTE = hDBPOVR_EFF_DTE;
	}
	public Date getHDBPOVR_END_DTE() {
		return HDBPOVR_END_DTE;
	}
	public void setHDBPOVR_END_DTE(Date hDBPOVR_END_DTE) {
		HDBPOVR_END_DTE = hDBPOVR_END_DTE;
	}
	public String getHDBPOVR_CNCL_RSN_CDE() {
		return HDBPOVR_CNCL_RSN_CDE;
	}
	public void setHDBPOVR_CNCL_RSN_CDE(String hDBPOVR_CNCL_RSN_CDE) {
		HDBPOVR_CNCL_RSN_CDE = hDBPOVR_CNCL_RSN_CDE;
	}
	public Double getHDBPOVR_OVRIDE_PRC() {
		return HDBPOVR_OVRIDE_PRC;
	}
	public void setHDBPOVR_OVRIDE_PRC(Double hDBPOVR_OVRIDE_PRC) {
		HDBPOVR_OVRIDE_PRC = hDBPOVR_OVRIDE_PRC;
	}
	public Double getHDBPOVR_OVRIDE_PRC_ANES() {
		return HDBPOVR_OVRIDE_PRC_ANES;
	}
	public void setHDBPOVR_OVRIDE_PRC_ANES(Double hDBPOVR_OVRIDE_PRC_ANES) {
		HDBPOVR_OVRIDE_PRC_ANES = hDBPOVR_OVRIDE_PRC_ANES;
	}
	public char getHDBPOVR_OVRIDE_RSN_CDE() {
		return HDBPOVR_OVRIDE_RSN_CDE;
	}
	public void setHDBPOVR_OVRIDE_RSN_CDE(char hDBPOVR_OVRIDE_RSN_CDE) {
		HDBPOVR_OVRIDE_RSN_CDE = hDBPOVR_OVRIDE_RSN_CDE;
	}
	public String getHDBPOVR_OVRIDE_RSN_TXT() {
		return HDBPOVR_OVRIDE_RSN_TXT;
	}
	public void setHDBPOVR_OVRIDE_RSN_TXT(String hDBPOVR_OVRIDE_RSN_TXT) {
		HDBPOVR_OVRIDE_RSN_TXT = hDBPOVR_OVRIDE_RSN_TXT;
	}
	public Date getHDBPOVR_LAST_UPDT_DTE() {
		return HDBPOVR_LAST_UPDT_DTE;
	}
	public void setHDBPOVR_LAST_UPDT_DTE(Date hDBPOVR_LAST_UPDT_DTE) {
		HDBPOVR_LAST_UPDT_DTE = hDBPOVR_LAST_UPDT_DTE;
	}
	public String getHDBPOVR_LAST_USERID() {
		return HDBPOVR_LAST_USERID;
	}
	public void setHDBPOVR_LAST_USERID(String hDBPOVR_LAST_USERID) {
		HDBPOVR_LAST_USERID = hDBPOVR_LAST_USERID;
	}
	
}
